import Footer from './components/Footer'
import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import RQProvider from './utils/RQProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CF App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <RQProvider>
          {children}
        </RQProvider>
        <Footer />
      </body>
    </html>
  )
}
